### ISSUE TITLE
Skelettierung

### ISSUE THREAD

**Issue by floriangfhws** [CReimer/fhws_ocr#1]
Die binarisierten Buchstaben müssen skelettiert werden.
Aus den Skelettierten Buchstaben entnehmen wir dann die Merkmale.

Edit: nur ein Gedanke... wenn wir Skelettieren, bevor wir Segmentieren bekommen wir vermutlich noch mehr Wörter gelesen. Schmalere Buchstaben = höhere Warscheinlichkeit auf "leere" Pixellinie zwischen den Zeichen.

**Comment by CReimer** [comment]
Ich habe mich damit jetzt mal ein wenig beschäftigt. Die Testdaten, die wir haben sind unbrauchbar. Um da ordentlich skelettieren zu können muss eine deutlich höhere Auflösung her.

Bei den jetzigen Testdaten hat ein einzelner Buchstabe schon weit unter 10 Pixel in der Breite, da ist nix mehr zu skelettieren.
